# Generated by Django 3.0.6 on 2020-05-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_answer_question_testtakers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtakers',
            old_name='correct_answers',
            new_name='correct_answer',
        ),
    ]
