# Generated by Django 3.0.6 on 2020-05-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_auto_20200509_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='testtakers',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='testtakers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TestTakers',
        ),
    ]
